### ISSUE TITLE
Suggestion: Increase effective radius based on hoe tier

### ISSUE THREAD

**Issue by YumatanGames** [wendall911/ActuallyHarvest#1]
Hi. I want to offer a suggestion to make your mod apart from all the other mods that offer the same thing: Radius.

If the player is holding a hoe while right clicking the crop, the mod will automatically harvest and replant in a radius equal to the tier of the hoe, centered around the targeted block. 

By hand: 1x1
Wooden Hoe: 2x2
Stone Hoe: 3x3
Iron Hoe: 4x4
Diamond Hoe: 5x5
Netherite Hoe: 6x6

Additionally, making that each level of the efficiency enchantment increases the radius by 1x1. 

This would make it so much more easy and satisfying to have huge farms. Imagine being able to automatically harvest and replant an 11x11 radius. Oh the dream... 

Thanks for your mod. 😄

**Comment by wendall911** [comment]
I was actually thinking of adding this. I even added a provision in code to allow for this. Thanks for the suggestion. I'll have something out soon.

**Comment by wendall911** [comment]
Ok, just pushed this up for 1.20.1, will follow up shortly with everything up through 1.21. I did make a change in favor of the Quark way. For the small tier (gold, wood, stone, iron) the expansion is 2 or a 3x3 and 3 or a 5x5 for (diamond/netherite). I did add expansions for each level of efficiency (which is probably unbalanced, but allows for a large expansion range. It is difficult to do expand by one from center, because I can only do this for 3x3, 5x5, 7x7, etc. I think it works well now, will need to do a little testing. Please let me know what you think.

**Comment by YumatanGames** [comment]
Sounds good. I'll try it as soon as I can. I'm currently playing 1.20.1 anyways, so that's actually perfect. 😁
